<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

   <!-- Inertia Macro -->
   <xacro:include filename="inertial_macros.xacro" />
   <!-- Wheel Macro -->
   <xacro:include filename="wheels_macro.xacro" />

   <!-- Cart Properties -->
   <xacro:property name="base_length" value = "1"/>
   <xacro:property name="base_width" value = "0.5"/>
   <xacro:property name="base_height" value = "0.5"/>
   <xacro:property name="base_mass" value = "1"/>

   <!-- Wheels Properties -->
   <xacro:property name="wheel_radius" value="0.1"/>
   <xacro:property name="wheel_width" value="0.02"/>
   <xacro:property name="wheel_xoff" value="0.3"/>
   <xacro:property name="wheel_yoff" value="0.01"/>
   <xacro:property name="wheel_zoff" value="0.1"/>
   <xacro:property name="wheel_mass" value="0.1"/>


   <!-- Links & Joints -->
   <link name="base_link">
      <!-- <visual>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
               <box size="0.01 0.01 0.01"/>
         </geometry>
         <material name="invisible">
               <color rgba="1 0 0 1"/>
         </material>
      </visual>
      <inertial>
         <mass value="0.001"/>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <inertia ixx="1e-6" ixy="0.0" ixz="0.0"
                  iyy="1e-6" iyz="0.0"
                  izz="1e-6"/>
      </inertial> -->
   </link>



   <joint name="cart_joint" type="fixed">
      <origin xyz="0.0 0.0 ${base_height/2 + wheel_radius + wheel_yoff}" rpy="0.0 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="cart_link"/>
      <axis xyz="1.0 0.0 0.0"/>
      <limit lower="-500.0" upper="500.0" effort="1000000.0" velocity="1.0"/>
   </joint>

   <link name="cart_link">
      <visual>
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
         <geometry>
               <box size="${base_length} ${base_width} ${base_height}"/>
         </geometry>
         <material name="Blue">
               <color rgba="0.0 0.0 1.0 1.0"/>
         </material>
      </visual>
      <collision>
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
         <geometry>
               <box size="${base_length} ${base_width} ${base_height}"/>
         </geometry>
      </collision>
      <xacro:inertial_box mass="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}">
         <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      </xacro:inertial_box>
   </link>

   <xacro:create_wheel prefix="rl_wheel" x_reflect="-1" y_reflect="1" x="${wheel_xoff}" y="${wheel_yoff}" z="${wheel_zoff}" b="${base_width}" r="${wheel_radius}" w="${wheel_width}" m="${wheel_mass}" />
   <xacro:create_wheel prefix="rr_wheel" x_reflect="-1" y_reflect="-1" x="${wheel_xoff}" y="${wheel_yoff}" z="${wheel_zoff}" b="${base_width}" r="${wheel_radius}" w="${wheel_width}" m="${wheel_mass}" />
   <xacro:create_wheel prefix="fl_wheel" x_reflect="1" y_reflect="1" x="${wheel_xoff}" y="${wheel_yoff}" z="${wheel_zoff}" b="${base_width}" r="${wheel_radius}" w="${wheel_width}" m="${wheel_mass}" />
   <xacro:create_wheel prefix="fr_wheel" x_reflect="1" y_reflect="-1" x="${wheel_xoff}" y="${wheel_yoff}" z="${wheel_zoff}" b="${base_width}" r="${wheel_radius}" w="${wheel_width}" m="${wheel_mass}" />

   <gazebo reference="base_link"/>

   <gazebo reference="cart_link"/>

   <gazebo reference="rl_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
   </gazebo>

   <gazebo reference="rr_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
   </gazebo>

   <gazebo reference="fl_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
   </gazebo>

   <gazebo reference="fr_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
   </gazebo>
   
</robot>